### ISSUE TITLE
module location hardcoding

### ISSUE THREAD

**Issue by liorkesos** [linnovate/elementor-drupal#19]
elementor expects to be called at /modules/elementor
It's common in drupal (composer does it) to install in modules/contrib and when I installed elementor there i had many wierd errors.
Symlinking from modules/elementor to modules/contrib/elementor solved the problem but the module shuld be more robust and resiliant.

**Comment by zohar** [comment]
Maybe use `drupal_get_path` ?https://api.drupal.org/api/drupal/core%21includes%21bootstrap.inc/function/drupal_get_path/8.6.x

**Comment by liorkesos** [comment]
Cloned latest version and it breaks if I place elementor in /contrib

**Comment by aronStein** [comment]
I could not reproduce the problem, please try install again
